package ucum

import (
	"testing"
	"github.com/smartystreets/goconvey/convey"
	"UCUM_Golang/ucum"
	"strconv"
	"github.com/smartystreets/assertions/should"
)

func TestRoundtripIntegerDecimal(t *testing.T){
	convey.Convey("TestRoundtripIntegerDecimal", t, func(){
		d,err := ucum.NewDecimal(strconv.Itoa(0))
		convey.So(err, should.BeNil)
		i,err := d.AsInteger()
		convey.So(err, should.BeNil)
		convey.So(i, should.Equal, 0)
		d,err = ucum.NewDecimal(strconv.Itoa(1))
		convey.So(err, should.BeNil)
		i,err = d.AsInteger()
		convey.So(err, should.BeNil)
		convey.So(i, should.Equal, 1)
		d,err = ucum.NewDecimal(strconv.Itoa(2))
		convey.So(err, should.BeNil)
		i,err = d.AsInteger()
		convey.So(err, should.BeNil)
		convey.So(i, should.Equal, 2)
		d,err = ucum.NewDecimal(strconv.Itoa(64))
		convey.So(err, should.BeNil)
		i,err = d.AsInteger()
		convey.So(err, should.BeNil)
		convey.So(i, should.Equal, 64)
		d,err = ucum.NewDecimal(strconv.Itoa(ucum.MAX_INT))
		convey.So(err, should.BeNil)
		i,err = d.AsInteger()
		convey.So(err, should.BeNil)
		convey.So(i, should.Equal, ucum.MAX_INT)
		d,err = ucum.NewDecimal(strconv.Itoa(-1))
		convey.So(err, should.BeNil)
		i,err = d.AsInteger()
		convey.So(err, should.BeNil)
		convey.So(i, should.Equal, -1)
		d,err = ucum.NewDecimal(strconv.Itoa(-2))
		convey.So(err, should.BeNil)
		i,err = d.AsInteger()
		convey.So(err, should.BeNil)
		convey.So(i, should.Equal, -2)
		d,err = ucum.NewDecimal(strconv.Itoa(-64))
		convey.So(err, should.BeNil)
		i,err = d.AsInteger()
		convey.So(err, should.BeNil)
		convey.So(i, should.Equal, -64)
		d,err = ucum.NewDecimal(strconv.Itoa(ucum.MIN_INT))
		convey.So(err, should.BeNil)
		i,err = d.AsInteger()
		convey.So(err, should.BeNil)
		convey.So(i, should.Equal, ucum.MIN_INT)
	})
}

func TestDecimalToString(t *testing.T) {
	convey.Convey("TestDecimalToString", t, func() {
		d, err := ucum.NewDecimal(strconv.Itoa(ucum.MIN_INT))
		convey.So(err, should.BeNil)
		s := d.String()
		convey.So(s, should.Equal, strconv.Itoa(ucum.MIN_INT))
		d, err = ucum.NewDecimal(strconv.Itoa(ucum.MAX_INT))
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, strconv.Itoa(ucum.MAX_INT))
		d, err = ucum.NewDecimal("1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1")
		d, err = ucum.NewDecimal("0")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0")
		d, err = ucum.NewDecimal("-0")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0")
		d, err = ucum.NewDecimal("10")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "10")
		d, err = ucum.NewDecimal("99")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "99")
		d, err = ucum.NewDecimal("-1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-1")
		d, err = ucum.NewDecimal("-10")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-10")
		d, err = ucum.NewDecimal("-99")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-99")
		d, err = ucum.NewDecimal("1.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1.1")
		d, err = ucum.NewDecimal("-1.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-1.1")
		d, err = ucum.NewDecimal("11.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "11.1")
		d, err = ucum.NewDecimal("1.11")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1.11")
		d, err = ucum.NewDecimal("1.111")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1.111")
		d, err = ucum.NewDecimal("0.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.1")
		d, err = ucum.NewDecimal("00.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.1")
		d, err = ucum.NewDecimal(".1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.1")
		d, err = ucum.NewDecimal("1.0")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1.0")
		d, err = ucum.NewDecimal("1.00")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1.00")
		d, err = ucum.NewDecimal("1.000000000000000000000000000000000000000")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1.000000000000000000000000000000000000000")
		d, err = ucum.NewDecimal("-11.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-11.1")
		d, err = ucum.NewDecimal("-1.11")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-1.11")
		d, err = ucum.NewDecimal("-1.111")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-1.111")
		d, err = ucum.NewDecimal("-0.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-0.1")
		d, err = ucum.NewDecimal("-00.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-0.1")
		d, err = ucum.NewDecimal("-.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-0.1")
		d, err = ucum.NewDecimal("-1.0")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-1.0")
		d, err = ucum.NewDecimal("-1.00")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-1.00")
		d, err = ucum.NewDecimal("-1.000000000000000000000000000000000000000")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-1.000000000000000000000000000000000000000")
		d, err = ucum.NewDecimal("0.0")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.0")
		d, err = ucum.NewDecimal("0.0000")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.0000")
		d, err = ucum.NewDecimal("0.100")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.100")
		d, err = ucum.NewDecimal("100")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "100")
		d, err = ucum.NewDecimal("0.01")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.01")
		d, err = ucum.NewDecimal("0.001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.001")
		d, err = ucum.NewDecimal("0.0001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.0001")
		d, err = ucum.NewDecimal("00.0001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.0001")
		d, err = ucum.NewDecimal("000.0001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.0001")
		d, err = ucum.NewDecimal("-0.01")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "-0.01")
		d, err = ucum.NewDecimal("10.01")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "10.01")
		d, err = ucum.NewDecimal("0.00001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.00001")
		d, err = ucum.NewDecimal("0.000001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.000001")
		d, err = ucum.NewDecimal("0.0000001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.0000001")
		d, err = ucum.NewDecimal("0.000000001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.000000001")
		d, err = ucum.NewDecimal("0.00000000001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.00000000001")
		d, err = ucum.NewDecimal("0.0000000000001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.0000000000001")
		d, err = ucum.NewDecimal("0.000000000000001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.000000000000001")
		d, err = ucum.NewDecimal("0.00000000000000001")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "0.00000000000000001")
		d, err = ucum.NewDecimal("10.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "10.1")
		d, err = ucum.NewDecimal("100.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "100.1")
		d, err = ucum.NewDecimal("1000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1000.1")
		d, err = ucum.NewDecimal("10000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "10000.1")
		d, err = ucum.NewDecimal("100000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "100000.1")
		d, err = ucum.NewDecimal("1000000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1000000.1")
		d, err = ucum.NewDecimal("10000000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "10000000.1")
		d, err = ucum.NewDecimal("100000000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "100000000.1")
		d, err = ucum.NewDecimal("1000000000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1000000000.1")
		d, err = ucum.NewDecimal("10000000000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "10000000000.1")
		d, err = ucum.NewDecimal("100000000000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "100000000000.1")
		d, err = ucum.NewDecimal("1000000000000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "1000000000000.1")
		d, err = ucum.NewDecimal("10000000000000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "10000000000000.1")
		d, err = ucum.NewDecimal("100000000000000.1")
		convey.So(err, should.BeNil)
		s = d.String()
		convey.So(s, should.Equal, "100000000000000.1")
	})
}
