// Code generated by "enumer -type=ConceptKind"; DO NOT EDIT

package ucum

import (
	"fmt"
)

const _ConceptKind_name = "PREFIXBASEUNITUNIT"

var _ConceptKind_index = [...]uint8{0, 6, 14, 18}

func (i ConceptKind) String() string {
	if i < 0 || i >= ConceptKind(len(_ConceptKind_index)-1) {
		return fmt.Sprintf("ConceptKind(%d)", i)
	}
	return _ConceptKind_name[_ConceptKind_index[i]:_ConceptKind_index[i+1]]
}

var _ConceptKindNameToValue_map = map[string]ConceptKind{
	_ConceptKind_name[0:6]:   0,
	_ConceptKind_name[6:14]:  1,
	_ConceptKind_name[14:18]: 2,
}

func ConceptKindString(s string) (ConceptKind, error) {
	if val, ok := _ConceptKindNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ConceptKind values", s)
}
